### ISSUE TITLE
ddi-json add fields: mode of collection, time method and sampling procedure

### ISSUE THREAD

**Issue by borsna** [MetadataTransform/ddi-xslt#1]
On the root level:

* Mode of collection (multiple and language coded)

``//d:ModeOfCollection/r:Content``

* Time method (multiple and language coded)

``//d:TimeMethod/r:Content``

* Sampling procedure (multiple and language coded)

``//d:SamplingProcedure/r:Content``

**Comment by ssvw** [comment]
Fixed _//d:TimeMethod/r:Content_ as _timemethod_.

**Comment by ssvw** [comment]
Fixed _//d:ModeOfCollection/r:Content_ as _modeofcollection_.

**Comment by ssvw** [comment]
Added _//d:SamplingProcedure/r:Content_ as _samplingprocedure_.
