### ISSUE TITLE
ddi-json DDI 3.1 Add property for country

### ISSUE THREAD

**Issue by borsna** [MetadataTransform/ddi-xslt#3]
If there is a value in 

``//r:GeographicLocation/r:Values/r:GeographyValue[r:GeographyCode/r:Value[@codeListID="ISO3166-1"]]/r:GeographyName[@xml:lang="en"]
``

add a property called ``country``

**Comment by ssvw** [comment]
Fixed. Default "Denmark" for @agency = dk.dda, default = empty string otherwise, i.e. if no value (according to above XPath expression is given.
